packages:
  - .
  - packages/*

linkWorkspacePackages: true
nodeLinker: hoisted
autoInstallPeers: true

allowBuilds:
  '@deepseek-ai/dsh-subprocess-local': true
  node-pty: true
  koffi: true
  node-addon-require-builtin: false
  '@google/genai': false
  protobufjs: false

patchedDependencies:
  '@deepseek-ai/dsh-client-ui-settings-models@0.1.1-rc.2': patches/@deepseek-ai__dsh-client-ui-settings-models@0.1.1-rc.2.patch
  '@deepseek-ai/dsh-user-approval@0.1.1-rc.2': patches/@deepseek-ai__dsh-user-approval@0.1.1-rc.2.patch
